parameters:
# ...

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Swift\Application\:
    resource: 'src/swift/Application/*'
    exclude: 'src/swift/Application/Bootstrap/*'