imports:
  - { resource: src/swift/services.yaml }

parameters:
  # ...

services:
  _defaults:
    autowire: false
    autoconfigure: true
    public: true

  Honeywell\:
    resource: 'app/Honeywell/*'