parameters:
# ...

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  HoneywellOld\:
    resource: 'app/honeywellOld/*'
    exclude: 'app/honeywellOld/{registration.php}'