parameters:
# ...

services:
  _defaults:
    autowire: false
    autoconfigure: true
    public: false

  Swift\Application\:
    resource: 'src/swift/Application/*'
    exclude: 'src/swift/Application/Bootstrap/*'