parameters:
# ...

services:
  _defaults:
    autowire: false
    autoconfigure: true
    public: false

  Swift\Application\:
    resource: 'vendor/henrivantsant/swift/src/Application/*'
    exclude: 'vendor/henrivantsant/swift/src/Application/Bootstrap/*'