parameters:
# ...

services:
  _defaults:
    autowire: false
    autoconfigure: true
    public: true

  Swift\:
    resource: '*'
    public: true
    exclude: [ 'Monolog/Logger', 'GraphQl_old', 'GraphQl2/*', 'GraphQl3/*', 'Doctrine/*', 'Application/Bootstrap/*', 'Application/Globals.php', 'Runtime/Server/server-bootstrap.php' ]