imports:
  - { resource: vendor/swift-api/swift/src/Application/services.yaml}

parameters:
# ...

services:
  _defaults:
    autowire: false
    autoconfigure: true
    public: true

  Swift\:
    resource: 'vendor/swift-api/swift/src/*'
    exclude: [ 'Monolog/Logger' ]